config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  get "restaurants/new", to: "restaurants#new"

  root to: "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurants = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # def show
  #  @reviews = Review.find(params[:id])
  # end

#  def new
#    @review = Review.new
#  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :"restaurants/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

  <div class="container">
    <h1> Lista de restaurantes em São Paulo</h1>
    <ul class = "restaurants_list">
    <% @restaurants.each do |restaurant| %>
      <li> <%= link_to "#{restaurant.name}", "restaurants/#{restaurant.id}"  %> </li>
    <% end %>
    </ul>
  </div>
  <br><br>
  <div class="link_new">
    <%= link_to "Registrar Novo Restaurante", restaurants_new_path %>
  </div>

</body>
</html>

app/views/restaurants/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

  <div class="container">
    <h1> Cadastro de restaurantes: </h1>
      <%= form_for(@restaurant) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :address %>
        <%= f.text_field :address %>
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number %>
        <%= f.label :category %>
        <%= f.text_field :category %>
        <%= f.submit %>
      <% end %>

  </div>




</body>
</html>

app/views/restaurants/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="container">
    <h1>Seja bem vindo ao restaurante </h1> <h2> <%= @restaurants.name %></h2>
    <h3> Endereço: </h3> <%= @restaurants.address %>
    <h3> Telefone: </h3> <%= @restaurants.phone_number %>
    <h3> Categoria: </h3> <%= @restaurants.category %>
  </div>
  <br><br><br>

  <br><br>

    <div class="link">
      <%= link_to "Retorne a Página Principal", restaurants_path %>
    </div>
</body>
</html>